#!/usr/bin/env python3
"""Export readable chapter Markdown files into manuscript outputs."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


DEFAULT_CONFIG: dict[str, Any] = {
    "project_name": "Long Novel Project",
    "chapter_prefix": "ch",
    "readable_dir": "readable",
    "exports_dir": "exports",
}


def load_config(path: str | None) -> dict[str, Any]:
    cfg = dict(DEFAULT_CONFIG)
    if path:
        p = Path(path).expanduser()
        data = json.loads(p.read_text(encoding="utf-8"))
        cfg.update(data)
    return cfg


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Export readable chapter files into manuscript outputs.")
    p.add_argument("--project-root", default=".")
    p.add_argument("--config", default=None, help="JSON config path.")
    p.add_argument("--source-dir", default=None, help="Override readable source directory.")
    p.add_argument("--exports-dir", default=None, help="Override exports directory.")
    p.add_argument("--volume", default="volume-01", help="Release volume id/name.")
    p.add_argument("--write-release", action="store_true", help="Also write exports/release/<volume>.md.")
    return p.parse_args()


def chapter_sort_key(path: Path, prefix: str) -> tuple[int, str]:
    m = re.match(rf"^{re.escape(prefix)}(\d+)(?:[-_].*)?\.md$", path.name)
    if m:
        return (int(m.group(1)), path.name)
    return (10**9, path.name)


def chapter_files(source: Path, prefix: str) -> list[Path]:
    if not source.exists():
        return []
    return sorted(source.glob(f"{prefix}*.md"), key=lambda p: chapter_sort_key(p, prefix))


def strip_markdown_for_txt(markdown: str) -> str:
    text = re.sub(r"^#{1,6}\s*", "", markdown, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    return text


def build_manuscript(paths: list[Path], project_name: str) -> str:
    parts = [f"# {project_name}", "", "<!-- Generated by scripts/export_manuscript.py -->", ""]
    if not paths:
        parts.extend(["> No readable chapter files found at export time.", ""])
        return "\n".join(parts)
    for idx, path in enumerate(paths):
        text = path.read_text(encoding="utf-8", errors="ignore").strip()
        if idx:
            parts.extend(["", "---", ""])
        parts.append(text)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    args = parse_args()
    root = Path(args.project_root).expanduser().resolve()
    cfg = load_config(args.config)
    prefix = cfg.get("chapter_prefix", "ch")
    source_dir = root / (args.source_dir or cfg.get("readable_dir", "readable"))
    exports_dir = root / (args.exports_dir or cfg.get("exports_dir", "exports"))
    exports_dir.mkdir(parents=True, exist_ok=True)

    chapters = chapter_files(source_dir, prefix)
    manuscript_md = build_manuscript(chapters, cfg.get("project_name", "Long Novel Project"))

    md_path = exports_dir / "manuscript.md"
    txt_path = exports_dir / "manuscript.txt"
    md_path.write_text(manuscript_md, encoding="utf-8")
    txt_path.write_text(strip_markdown_for_txt(manuscript_md), encoding="utf-8")

    print(f"Project root: {root}")
    print(f"Source dir: {source_dir}")
    print(f"Chapters exported: {len(chapters)}")
    print(f"OK: wrote {md_path}")
    print(f"OK: wrote {txt_path}")

    if args.write_release:
        release_dir = exports_dir / "release"
        release_dir.mkdir(parents=True, exist_ok=True)
        release_path = release_dir / f"{args.volume}.md"
        release_path.write_text(manuscript_md, encoding="utf-8")
        print(f"OK: wrote {release_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
